### ISSUE TITLE
specielle tegn i ordet

### ISSUE THREAD

**Issue by Thanerik** [Wign/Wign#21]
Lave `/` om til `&#47;` og andre lignende tegn skal også laves om til html kode. For at undgå fejlbeskeder og forvirringer i routes.

**Comment by Ansty93** [comment]
Yes du har nok allerede bemærket det selv.
Linket : http://www.wign.dk/tegn/supertotal_/_long_or_wide_shot

**Comment by Thanerik** [comment]
Præcis 😄

**Comment by Thanerik** [comment]
Fixed in 6146a39a2774dfa5baeb29d9ba8a593c1ecb2144
