### ISSUE TITLE
Speciel symbol som en del af søgestreng virker ikke

### ISSUE THREAD

**Issue by Kennik89** [Wign/Wign#57]
Jeg har oprettet et tegn for C#, hvor i linket står der "...C#", men jeg bliver henvist til siden med tegn af C.
http://www.wign.dk/tegn/c#

**Comment by Thanerik** [comment]
Hmm... Eller, den virker. Da det stadig er c# i linket. Men det er overskriften som vælger at frasortere symbolet...
