### ISSUE TITLE
Ny linje i beskrivelse-feltet fjernes ved fremvisning af tegn

### ISSUE THREAD

**Issue by Kennik89** [Wign/Wign#58]
I bemærkningsfelten skal der være muligt at indsætte nye linjer for at konteksten kan give bedre mening, hvis nødvendigt/efter behov

**Comment by Thanerik** [comment]
Enig. Kigger på det

**Comment by Thanerik** [comment]
Fixed in commit 85f69b2e3bfec43943d74faaa50d2f0555e68f72
